import 'package:flutter/foundation.dart';
import '../../data/models/availability.dart';
import '../../data/repositories/availability_repository.dart';

class AvailabilityController extends ChangeNotifier {
  final AvailabilityRepository _repository;

  AvailabilityController(this._repository);

  List<Availability> _availabilities = [];
  bool _isLoading = false;
  String? _error;

  List<Availability> get availabilities => _availabilities;
  bool get isLoading => _isLoading;
  String? get error => _error;

  /// Load availabilities for a goalkeeper
  Future<void> loadAvailabilities(String goalkeeperId) async {
    _setLoading(true);
    _clearError();

    try {
      _availabilities = await _repository.getGoalkeeperAvailabilities(goalkeeperId);
      notifyListeners();
    } catch (e) {
      _setError(e.toString());
    } finally {
      _setLoading(false);
    }
  }

  /// Load only future availabilities
  Future<void> loadFutureAvailabilities(String goalkeeperId) async {
    _setLoading(true);
    _clearError();

    try {
      _availabilities = await _repository.getFutureAvailabilities(goalkeeperId);
      notifyListeners();
    } catch (e) {
      _setError(e.toString());
    } finally {
      _setLoading(false);
    }
  }

  /// Add a new availability
  Future<bool> addAvailability({
    required String goalkeeperId,
    required DateTime day,
    required String startTime,
    required String endTime,
  }) async {
    _clearError();

    try {
      // Check for time conflicts first
      final hasConflict = await _repository.hasTimeConflict(
        goalkeeperId: goalkeeperId,
        day: day,
        startTime: startTime,
        endTime: endTime,
      );

      if (hasConflict) {
        _setError('Já existe disponibilidade neste horário.');
        return false;
      }

      final availability = Availability(
        id: '', // Will be generated by Supabase
        goalkeeperId: goalkeeperId,
        day: day,
        startTime: startTime,
        endTime: endTime,
      );

      final newAvailability = await _repository.addAvailability(availability);
      
      // Add to local list and sort
      _availabilities.add(newAvailability);
      _sortAvailabilities();
      notifyListeners();
      
      return true;
    } catch (e) {
      _setError(e.toString());
      return false;
    }
  }

  /// Update an existing availability
  Future<bool> updateAvailability(Availability availability) async {
    _clearError();

    try {
      // Check for time conflicts (excluding current availability)
      final hasConflict = await _repository.hasTimeConflict(
        goalkeeperId: availability.goalkeeperId,
        day: availability.day,
        startTime: availability.startTime,
        endTime: availability.endTime,
        excludeAvailabilityId: availability.id,
      );

      if (hasConflict) {
        _setError('Já existe disponibilidade neste horário.');
        return false;
      }

      final updatedAvailability = await _repository.updateAvailability(availability);
      
      // Update in local list
      final index = _availabilities.indexWhere((a) => a.id == availability.id);
      if (index != -1) {
        _availabilities[index] = updatedAvailability;
        _sortAvailabilities();
        notifyListeners();
      }
      
      return true;
    } catch (e) {
      _setError(e.toString());
      return false;
    }
  }

  /// Delete an availability
  Future<bool> deleteAvailability(String availabilityId) async {
    _clearError();

    try {
      await _repository.deleteAvailability(availabilityId);
      
      // Remove from local list
      _availabilities.removeWhere((a) => a.id == availabilityId);
      notifyListeners();
      
      return true;
    } catch (e) {
      _setError(e.toString());
      return false;
    }
  }

  /// Get availabilities for a specific date
  List<Availability> getAvailabilitiesForDate(DateTime date) {
    return _availabilities.where((availability) {
      return availability.day.year == date.year &&
          availability.day.month == date.month &&
          availability.day.day == date.day;
    }).toList();
  }

  /// Get availabilities grouped by date
  Map<DateTime, List<Availability>> get availabilitiesByDate {
    final Map<DateTime, List<Availability>> grouped = {};
    
    for (final availability in _availabilities) {
      final date = DateTime(availability.day.year, availability.day.month, availability.day.day);
      
      if (!grouped.containsKey(date)) {
        grouped[date] = [];
      }
      grouped[date]!.add(availability);
    }
    
    // Sort availabilities within each date
    for (final availabilities in grouped.values) {
      availabilities.sort((a, b) => a.startTime.compareTo(b.startTime));
    }
    
    return grouped;
  }

  /// Clear all data
  void clear() {
    _availabilities.clear();
    _error = null;
    _isLoading = false;
    notifyListeners();
  }

  /// Refresh availabilities
  Future<void> refresh(String goalkeeperId) async {
    await loadFutureAvailabilities(goalkeeperId);
  }

  void _setLoading(bool loading) {
    _isLoading = loading;
    notifyListeners();
  }

  void _setError(String error) {
    _error = error;
    notifyListeners();
  }

  void _clearError() {
    _error = null;
    notifyListeners();
  }

  void _sortAvailabilities() {
    _availabilities.sort((a, b) {
      final dateComparison = a.day.compareTo(b.day);
      if (dateComparison != 0) return dateComparison;
      return a.startTime.compareTo(b.startTime);
    });
  }
}
